[package]
name = "ssd1306-sysinfo-display"
version = "0.1.0"
edition.workspace = true
description = "Port of Adafruit's SSD1306 Python driver and sysinfo example"

[dependencies]
ssd1306-driver-rs = { path = "../ssd1306-driver-rs", features = ["graphics"] }
embedded-graphics = { workspace = true }
rppal = { version = "0.22.1", features = ["embedded-hal"] }
